# ダンジョン設定ファイル
dungeons:
  # 初心者向けダンジョン
  beginners_cave:
    name: "始まりの洞窟"
    description: "冒険者たちが最初に挑戦する洞窟です。\n比較的弱い魔物が生息しています。"
    difficulty: 1
    min_level: 1
    max_level: 5
    recommended_level: "1-3"
    attribute: "物理"
    floors: 5
    seed_base: "beginners_cave"
    unlock_condition: "always"  # 常にアンロック
    
  # 中級者向けダンジョン
  ancient_ruins:
    name: "古の遺跡"
    description: "古代文明の遺跡です。\n魔法の力を持つ魔物が多く現れます。"
    difficulty: 2
    min_level: 4
    max_level: 10
    recommended_level: "6-8"
    attribute: "魔法"
    floors: 8
    seed_base: "ancient_ruins"
    unlock_condition: "level_5"  # パーティの最高レベルが5以上
    
  # 上級者向けダンジョン
  demon_labyrinth:
    name: "魔の迷宮"
    description: "強力な魔物たちが住む迷宮です。\n豊富な宝物が眠っていると言われています。"
    difficulty: 3
    min_level: 10
    max_level: 15
    recommended_level: "12-14"
    attribute: "闇"
    floors: 12
    seed_base: "demon_labyrinth"
    unlock_condition: "level_10"  # パーティの最高レベルが10以上
    
  # 最高難易度ダンジョン  
  dragon_lair:
    name: "竜の巣窟"
    description: "伝説の竜が眠ると言われる最深の洞窟です。\n最強の冒険者のみが挑戦できます。"
    difficulty: 4
    min_level: 15
    max_level: 20
    recommended_level: "18-20"
    attribute: "炎"
    floors: 20
    seed_base: "dragon_lair"
    unlock_condition: "level_15"  # パーティの最高レベルが15以上
    
  # デフォルトダンジョン（互換性維持）
  main_dungeon:
    name: "練習用ダンジョン"
    description: "開発用の基本ダンジョンです。"
    difficulty: 1
    min_level: 1
    max_level: 20
    recommended_level: "1-20"
    attribute: "物理"
    floors: 20
    seed_base: "main_dungeon"
    unlock_condition: "always"

# ダンジョンのアンロック条件
unlock_conditions:
  always: "常に利用可能"
  level_5: "パーティの最高レベルが5以上"
  level_10: "パーティの最高レベルが10以上"
  level_15: "パーティの最高レベルが15以上"
  boss_defeated: "特定のボスを撃破"