analog_deadzone: 0.3
analog_sensitivity: 1.0
auto_save: true
battle_speed: normal
color_blind_mode: none
confirm_actions: true
controller_enabled: true
difficulty: normal
feedback_level: normal
fullscreen: false
high_contrast: false
keyboard_enabled: true
language: en
large_text: false
master_volume: 0.9
message_speed: normal
music_volume: 0.8
mute_on_focus_loss: true
resolution: 1024x768
screen_reader: false
sfx_volume: 0.9
show_fps: false
ui_scale: 1.0
vibration_enabled: true
voice_volume: 1.0
vsync: true
