# English Text

# Application
app:
  title: "Dungeon Explorer"

# Menu & UI
menu:
  main_menu: "Main Menu"
  new_game: "New Game"
  load_game: "Load Game"
  save_game: "Save Game"
  settings: "Settings"
  exit: "Exit"
  back: "Back"
  facilities: "Facilities"
  party_status: "Party Status"
  game_settings: "Game Settings"
  
# Common
common:
  yes: "Yes"
  no: "No"
  ok: "OK"
  cancel: "Cancel"
  confirm: "Confirm"
  error: "Error"
  warning: "Warning"
  info: "Info"
  
# Character
character:
  name: "Name"
  level: "Level"
  hp: "HP"
  mp: "MP"
  strength: "Strength"
  agility: "Agility"
  intelligence: "Intelligence"
  faith: "Faith"
  luck: "Luck"
  enter_name: "Enter Name"
  select_race: "Select Race"
  select_class: "Select Class"
  
# Race
race:
  human: "Human"
  elf: "Elf"
  dwarf: "Dwarf"
  hobbit: "Hobbit"
  
# Class
class:
  fighter: "Fighter"
  mage: "Mage"
  priest: "Priest"
  thief: "Thief"
  bishop: "Bishop"
  samurai: "Samurai"
  lord: "Lord"
  ninja: "Ninja"
  
# Facilities
facility:
  guild: "Adventurers Guild"
  inn: "Inn"
  shop: "Shop"
  temple: "Temple"
  magic_guild: "Magic Guild"
  dungeon_entrance: "Dungeon Entrance"

# Overworld
overworld:
  town_center: "Town Center"
  surface_map: "Surface"
  facility_selection: "Facility Selection"
  
# System Messages
system:
  loading: "Loading..."
  saving: "Saving..."
  game_saved: "Game Saved"
  game_loaded: "Game Loaded"
  startup: "Starting Game"
  shutdown: "Shutting Down"

# Dungeon related
dungeon:
  entrance_error_title: "Dungeon Entrance Error"
  entrance_error_prefix: "Unable to enter dungeon:"