# 日本語テキスト

# メニュー・UI
menu:
  main_menu: "メインメニュー"
  new_game: "新しいゲーム"
  load_game: "ゲームをロード"
  save_game: "ゲームを保存"
  settings: "設定"
  exit: "終了"
  back: "戻る"
  
# ゲーム共通
common:
  yes: "はい"
  no: "いいえ"
  ok: "OK"
  cancel: "キャンセル"
  confirm: "確認"
  error: "エラー"
  warning: "警告"
  info: "情報"
  
# キャラクター関連
character:
  name: "名前"
  level: "レベル"
  hp: "HP"
  mp: "MP"
  strength: "力"
  agility: "素早さ"
  intelligence: "知恵"
  faith: "信仰心"
  luck: "運"
  
# 種族
race:
  human: "人間"
  elf: "エルフ"
  dwarf: "ドワーフ"
  hobbit: "ホビット"
  
# 職業
class:
  fighter: "戦士"
  mage: "魔術師"
  priest: "僧侶"
  thief: "盗賊"
  bishop: "司教"
  samurai: "侍"
  lord: "君主"
  ninja: "忍者"
  
# 地上部施設
facility:
  guild: "冒険者ギルド"
  inn: "宿屋"
  shop: "商店"
  temple: "教会"
  magic_guild: "魔術師ギルド"
  dungeon_entrance: "ダンジョン入口"
  
# システムメッセージ
system:
  loading: "読み込み中..."
  saving: "保存中..."
  game_saved: "ゲームを保存しました"
  game_loaded: "ゲームをロードしました"
  startup: "ゲームを開始します"
  shutdown: "ゲームを終了します"