# 日本語テキスト

# アプリケーション
app:
  title: "ダンジョンエクスプローラー"

# メニュー・UI
menu:
  main_menu: "メインメニュー"
  new_game: "新しいゲーム"
  load_game: "ゲームをロード"
  save_game: "ゲームを保存"
  settings: "設定"
  exit: "終了"
  back: "戻る"
  facilities: "施設選択"
  party_status: "パーティ状況"
  game_settings: "ゲーム設定"
  
# ゲーム共通
common:
  "yes": "はい"
  "no": "いいえ"
  ok: "OK"
  cancel: "キャンセル"
  confirm: "確認"
  error: "エラー"
  warning: "警告"
  info: "情報"
  back: "戻る"
  close: "閉じる"
  empty: "(空)"
  view_details: "詳細を見る"
  unknown: "不明"
  
# キャラクター関連
character:
  name: "名前"
  level: "レベル"
  hp: "HP"
  mp: "MP"
  strength: "力"
  agility: "素早さ"
  intelligence: "知恵"
  faith: "信仰心"
  luck: "運"
  enter_name: "名前入力"
  select_race: "種族選択"
  select_class: "クラス選択"
  
# 種族
race:
  human: "人間"
  elf: "エルフ"
  dwarf: "ドワーフ"
  hobbit: "ホビット"
  human_desc: "バランスの取れた能力を持つ"
  elf_desc: "魔法に優れ、素早い"
  dwarf_desc: "力強く、信仰心が厚い"
  hobbit_desc: "幸運に恵まれた小柄な民族"
  
# 職業
class:
  fighter: "戦士"
  mage: "魔術師"
  priest: "僧侶"
  thief: "盗賊"
  bishop: "司教"
  samurai: "侍"
  lord: "君主"
  ninja: "忍者"
  fighter_desc: "近接戦闘のエキスパート"
  mage_desc: "攻撃魔法の使い手"
  priest_desc: "回復・補助魔法の専門家"
  thief_desc: "敏捷性と特殊技能に優れる"
  bishop_desc: "魔法と祈祷の両方を使える"
  samurai_desc: "武士道を極めた戦士"
  lord_desc: "指導力に優れた貴族"
  ninja_desc: "隠密と暗殺の達人"

# キャラクター作成
character:
  creation_title: "キャラクター作成"
  enter_name: "名前を入力してください"
  enter_name_detail: "キャラクターの名前を入力してください:"
  select_race: "種族を選択"
  select_class: "職業を選択"
  generated_stats: "能力値"
  reroll: "振り直し"
  confirm_creation: "作成確認"
  create: "作成"

# アイテム
item:
  dagger: "ダガー"
  dagger_desc: "軽量で扱いやすい短剣"
  short_sword: "ショートソード"
  short_sword_desc: "バランスの取れた短剣"
  long_sword: "ロングソード"
  long_sword_desc: "威力の高い長剣"
  mace: "メイス"
  mace_desc: "重厚な打撃武器"
  staff: "スタッフ"
  staff_desc: "魔法の威力を高める杖"
  bow: "ボウ"
  bow_desc: "遠距離攻撃が可能な弓"
  cloth_robe: "布のローブ"
  cloth_robe_desc: "魔法使いが着る軽装"
  leather_armor: "レザーアーマー"
  leather_armor_desc: "軽量で動きやすい革鎧"
  chain_mail: "チェインメイル"
  chain_mail_desc: "鎖でできた防具"
  plate_armor: "プレートアーマー"
  plate_armor_desc: "最高の防御力を誇る重装"
  healing_potion: "回復ポーション"
  healing_potion_desc: "HPを回復する薬"
  mana_potion: "マナポーション"
  mana_potion_desc: "MPを回復する薬"
  antidote: "解毒剤"
  antidote_desc: "毒を治療する薬"
  return_scroll: "帰還の巻物"
  return_scroll_desc: "町に帰還できる巻物"
  resurrection_powder: "蘇生の粉"
  resurrection_powder_desc: "死者を蘇らせる貴重な粉"
  fire_spell_book: "ファイアの魔法書"
  fire_spell_book_desc: "火炎魔法を習得できる"
  heal_prayer_book: "ヒールの祈祷書"
  heal_prayer_book_desc: "回復祈祷を習得できる"
  lockpick: "鍵開け道具"
  lockpick_desc: "鍵のかかった扉や宝箱を開ける"
  torch: "松明"
  torch_desc: "暗闇を照らす"

# 魔法・祈祷
spell:
  fire: "ファイア"
  fire_desc: "敵1体に火炎ダメージを与える"
  fireball: "ファイアボール"
  fireball_desc: "敵グループに火炎ダメージを与える"
  ice_storm: "アイスストーム"
  ice_storm_desc: "全ての敵に氷雪ダメージを与える"
  lightning: "ライトニング"
  lightning_desc: "敵1体に雷撃ダメージを与える"
  heal: "ヒール"
  heal_desc: "味方1体のHPを回復する"
  cure: "キュア"
  cure_desc: "味方1体の状態異常を治療する"
  bless: "ブレス"
  bless_desc: "味方1体の能力を一時的に向上させる"
  greater_heal: "グレーターヒール"
  greater_heal_desc: "味方1体のHPを大幅に回復する"
  group_heal: "グループヒール"
  group_heal_desc: "全ての味方のHPを回復する"
  resurrection: "リザレクション"
  resurrection_desc: "死亡した味方1体を蘇生する"
  light: "ライト"
  light_desc: "暗闇を照らし、探索を助ける"
  detect_magic: "ディテクトマジック"
  detect_magic_desc: "魔法のアイテムや罠を感知する"
  teleport: "テレポート"
  teleport_desc: "パーティを町に瞬間移動させる"
  dispel: "ディスペル"
  dispel_desc: "対象のバフ・デバフ効果を解除する"
  meteor: "メテオ"
  meteor_desc: "全ての敵に隕石による大ダメージを与える"
  divine_intervention: "神の加護"
  divine_intervention_desc: "全ての味方を完全回復させる"
  time_stop: "タイムストップ"
  time_stop_desc: "時間を止めて追加行動を得る"
  
# 地上部施設
facility:
  guild: "冒険者ギルド"
  inn: "宿屋"
  shop: "商店"
  temple: "教会"
  magic_guild: "魔術師ギルド"
  dungeon_entrance: "ダンジョン入口"

# 地上部
overworld:
  town_center: "町の中心部"
  surface_map: "地上"
  facility_selection: "施設選択"

# インベントリ
inventory:
  party_title: "パーティインベントリ"
  shared_items: "パーティ共有アイテム"
  item_management: "アイテム整理"
  slot_empty: "(空)"
  unidentified_item: "未鑑定の{item_type}"
  slot_usage: "使用中: {used}/{max}"
  use_item: "使用する"
  equip_item: "装備する"
  move_item: "別の場所に移動"
  drop_item: "破棄する"
  unidentified_header: "【未鑑定のアイテム】"
  item_header: "【{name}】"
  description_label: "説明"
  type_label: "種類"
  quantity_label: "数量"
  weight_label: "重量"
  value_label: "価値"

# 装備
equipment:
  party_title: "パーティ装備"
  party_stats: "パーティ装備統計"
  character_title: "{name}の装備"
  bonus_details: "装備ボーナス詳細"
  effect_check: "装備効果確認"
  slot:
    weapon: "武器"
    armor: "防具"
    accessory1: "アクセサリ1"
    accessory2: "アクセサリ2"

# 魔法
magic:
  party_title: "パーティ魔法管理"
  slot_management: "魔法スロット管理"
  learned_spells: "習得済み魔法一覧"
  spell_usage: "魔法使用"
  stats_details: "魔法統計・詳細"
  school:
    mage: "魔術"
    priest: "神聖"
    both: "汎用"
  type:
    offensive: "攻撃"
    healing: "回復"
    buff: "強化"
    debuff: "弱体化"
    utility: "汎用"
    revival: "蘇生"
    ultimate: "究極"

# ダンジョン
dungeon:
  menu:
    inventory: "インベントリ"
    magic: "魔法"
    equipment: "装備"
    camp: "キャンプ"
    status: "ステータス"
    status_effects: "状態効果"
    return_overworld: "地上部に戻る"

# 設定
settings:
  category:
    gameplay: "ゲームプレイ"
    controls: "操作設定"
    audio: "音声設定"
    graphics: "表示設定"
    accessibility: "アクセシビリティ"

# ステータス
stats:
  strength: "筋力"
  agility: "敏捷性"
  intelligence: "知力"
  faith: "信仰"
  luck: "運"
  attack_power: "攻撃力"
  defense: "防御力"
  magic_power: "魔法力"
  magic_resistance: "魔法抵抗"
  
# システムメッセージ
system:
  loading: "読み込み中..."
  saving: "保存中..."
  game_saved: "ゲームを保存しました"
  game_loaded: "ゲームをロードしました"
  startup: "ゲームを開始します"
  shutdown: "ゲームを終了します"
  exit_confirm: "ゲームを終了しますか？"