# 日本語テキスト

# メニュー・UI
menu:
  main_menu: "メインメニュー"
  new_game: "新しいゲーム"
  load_game: "ゲームをロード"
  save_game: "ゲームを保存"
  settings: "設定"
  exit: "終了"
  back: "戻る"
  
# ゲーム共通
common:
  yes: "はい"
  no: "いいえ"
  ok: "OK"
  cancel: "キャンセル"
  confirm: "確認"
  error: "エラー"
  warning: "警告"
  info: "情報"
  
# キャラクター関連
character:
  name: "名前"
  level: "レベル"
  hp: "HP"
  mp: "MP"
  strength: "力"
  agility: "素早さ"
  intelligence: "知恵"
  faith: "信仰心"
  luck: "運"
  
# 種族
race:
  human: "人間"
  elf: "エルフ"
  dwarf: "ドワーフ"
  hobbit: "ホビット"
  human_desc: "バランスの取れた能力を持つ"
  elf_desc: "魔法に優れ、素早い"
  dwarf_desc: "力強く、信仰心が厚い"
  hobbit_desc: "幸運に恵まれた小柄な民族"
  
# 職業
class:
  fighter: "戦士"
  mage: "魔術師"
  priest: "僧侶"
  thief: "盗賊"
  bishop: "司教"
  samurai: "侍"
  lord: "君主"
  ninja: "忍者"
  fighter_desc: "近接戦闘のエキスパート"
  mage_desc: "攻撃魔法の使い手"
  priest_desc: "回復・補助魔法の専門家"
  thief_desc: "敏捷性と特殊技能に優れる"
  bishop_desc: "魔法と祈祷の両方を使える"
  samurai_desc: "武士道を極めた戦士"
  lord_desc: "指導力に優れた貴族"
  ninja_desc: "隠密と暗殺の達人"

# キャラクター作成
character:
  creation_title: "キャラクター作成"
  enter_name: "名前を入力"
  select_race: "種族を選択"
  select_class: "職業を選択"
  generated_stats: "能力値"
  reroll: "振り直し"
  confirm_creation: "作成確認"
  create: "作成"
  
# 地上部施設
facility:
  guild: "冒険者ギルド"
  inn: "宿屋"
  shop: "商店"
  temple: "教会"
  magic_guild: "魔術師ギルド"
  dungeon_entrance: "ダンジョン入口"
  
# システムメッセージ
system:
  loading: "読み込み中..."
  saving: "保存中..."
  game_saved: "ゲームを保存しました"
  game_loaded: "ゲームをロードしました"
  startup: "ゲームを開始します"
  shutdown: "ゲームを終了します"